spring.application.name=flow-forge

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/flowforge?createDatabaseIfNotExist=true}
spring.datasource.username=root
spring.datasource.password=Azizsakib123#@!
spring.jpa.hibernate.ddl-auto=update
